### ISSUE TITLE
YAMLException: end of the stream or a document separator is expected at line 5

### ISSUE THREAD

**Issue by lefthandkick** [cheaty-sheet/pcheaty#3]
Hello, 

Like the concept.  Install plugin.  The preview window opens with is an error:
"YAMLException: end of the stream or a document separator is expected at line 5..."

I look through the repo, best I could... no joy.  

I must be missing something simple...?

Many thanks

**Comment by PPACI** [comment]
If I remember correctly, the preview won’t work until you have the basic cheat in your editor.

You can bootstrap it with snippets included in the plugin 👍

**Comment by PPACI** [comment]
I guess it's time to finally write a readme 🤷‍♂️
